"""empty message

Revision ID: 71655948f2fb
Revises: adfc2e54968a
Create Date: 2024-04-21 22:09:50.913987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71655948f2fb'
down_revision: Union[str, None] = 'adfc2e54968a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('task',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('Deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_user', sa.Integer(), nullable=True),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['assigned_user'], ['user.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')
    # ### end Alembic commands ###
